### ISSUE TITLE
Recompile for 4.15 -- Horizon?

### ISSUE THREAD

**Issue by JoshLammi** [xenonsmurf/Ashita4-Plugins#1]
No issues with Ashita 4.14, but I recently updated my Horizon build to 4.15 as many addons are starting to compile with it. Any chance of compiling DiscordRPC - Horizon in 4.15 for those of us who have done the same?

Cheers, love your work.

**Comment by Xenonsmurf** [comment]
Did you try the version for retail? Should work.

**Comment by Xenonsmurf** [comment]
i've closed this issue, as you can use either version, there's no difference other than HorizionXI is using 4.14,
