### ISSUE TITLE
Incorrect Game Title Formatting

### ISSUE THREAD

**Issue by Noikar** [xenonsmurf/Ashita4-Plugins#2]
I feel like the title should say FINAL FANTASY XI as that's the correct trademark typing or whatever. Also it would make it match the normal discord activity  
![image](https://user-images.githubusercontent.com/38861984/227309823-60538c8d-f622-4976-bfe3-94f9bdb35db5.png)

**Comment by Xenonsmurf** [comment]
done.

regards
mike

**Comment by Xenonsmurf** [comment]
this is handled via discord's dev portal, so you don't need to download a new version.

**Comment by Noikar** [comment]
Thanks dude you're amazing :)
